global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:14269"]

  - job_name: "apisix"
    static_configs:
      - targets: ["apisix:9091"]
