---
plugins:
- proxy-rewrite
- cors
- ext-plugin-pre-req
ext-plugin:
  path_for_test: /tmp/runner.sock
deployment:
  etcd:
    prefix: /apisix
    host:
    - http://127.0.0.1:2379
    tls:
      verify: true
    watch_timeout: 50
    startup_retry: 2
    timeout: 30
  role: traditional
  role_traditional:
    config_provider: yaml
  config_provider: yaml
  admin:
    enable_admin_cors: true
    admin_api_version: v3
    allow_admin:
    - 127.0.0.0/24
    admin_key:
    - name: admin
      key: HckytydqlxbjpwhnthnzxAUhImHtwvAp
      role: admin
    admin_listen:
      port: 9180
      ip: 0.0.0.0
    enable_admin_ui: true
    admin_key_required: true
nginx_config:
  http:
    enable_access_log: true
    access_log: logs/access.log
    underscores_in_headers: 'on'
    access_log_format: $remote_addr - $remote_user [$time_local] $http_host "$request"
      $status $body_bytes_sent $request_time "$http_referer" "$http_user_agent" $upstream_addr
      $upstream_status $upstream_response_time "$upstream_scheme://$upstream_host$upstream_uri"
    access_log_format_escape: default
    real_ip_from:
    - 127.0.0.1
    - 'unix:'
    proxy_ssl_server_name: true
    charset: utf-8
    variables_hash_max_size: 2048
    upstream:
      keepalive_timeout: 60s
      keepalive_requests: 1000
      keepalive: 320
    lua_shared_dict:
      plugin-ai-rate-limiting: 10m
      plugin-ai-rate-limiting-reset-header: 10m
      ext-plugin: 1m
      mcp-session: 10m
      ocsp-stapling: 10m
      cas-auth: 10m
      tars: 1m
      prometheus-metrics: 10m
      discovery: 1m
      plugin-limit-req: 10m
      plugin-limit-count: 10m
      plugin-limit-conn: 10m
      plugin-limit-req-redis-cluster-slot-lock: 1m
      plugin-limit-count-redis-cluster-slot-lock: 1m
      plugin-limit-conn-redis-cluster-slot-lock: 1m
      tracing_buffer: 10m
      plugin-api-breaker: 10m
      jwks: 1m
      introspection: 10m
      access-tokens: 1m
      internal-status: 10m
      upstream-healthcheck: 10m
      worker-events: 10m
      lrucache-lock: 10m
      balancer-ewma: 10m
      balancer-ewma-locks: 10m
      balancer-ewma-last-touched-at: 10m
      etcd-cluster-health-check: 10m
    real_ip_recursive: 'off'
    real_ip_header: X-Real-IP
    access_log_buffer: 16384
    client_max_body_size: 0
    keepalive_timeout: 60s
    send_timeout: 10s
    client_header_timeout: 60s
    client_body_timeout: 60s
  stream:
    enable_access_log: false
    access_log: logs/access_stream.log
    lua_shared_dict:
      plugin-limit-conn-stream: 10m
      worker-events-stream: 10m
      tars-stream: 1m
      upstream-healthcheck-stream: 10m
      etcd-cluster-health-check-stream: 10m
      lrucache-lock-stream: 10m
    access_log_format: $remote_addr [$time_local] $protocol $status $bytes_sent $bytes_received
      $session_time $apisix_request_id
    access_log_format_escape: default
  main_configuration_snippet: ''
  http_configuration_snippet: ''
  http_server_configuration_snippet: ''
  http_server_location_configuration_snippet: ''
  error_log_level: warn
  worker_processes: auto
  enable_cpu_affinity: false
  worker_rlimit_nofile: 20480
  worker_shutdown_timeout: 240s
  max_pending_timers: 16384
  max_running_timers: 4096
  stream_configuration_snippet: ''
  meta:
    lua_shared_dict:
      status-report: 1m
      prometheus-cache: 10m
      standalone-config: 10m
      prometheus-metrics: 15m
  event:
    worker_connections: 10620
  http_end_configuration_snippet: ''
  error_log: logs/error.log
  http_admin_configuration_snippet: ''
apisix:
  enable_control: true
  proxy_mode: http
  node_listen: 9080
  normalize_uri_like_servlet: false
  enable_reuseport: true
  enable_ipv6: false
  extra_lua_path: ''
  extra_lua_cpath: ''
  data_encryption:
    keyring:
    - qeddd145sfvddff3
    - edd1c9f0985e76a2
    enable_encrypt_fields: true
  enable_server_tokens: true
  disable_upstream_healthcheck: false
  lru:
    secret:
      ttl: 300
      count: 512
      neg_count: 512
      neg_ttl: 60
  router:
    http: radixtree_host_uri
    ssl: radixtree_sni
  worker_startup_time_threshold: 60
  disable_sync_configuration_during_start: false
  resolver_timeout: 5
  enable_http2: true
  delete_uri_tail_slash: false
  show_upstream_status_in_response_header: false
  ssl:
    enable: true
    ssl_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl_session_tickets: false
    listen:
    - enable_http3: false
      port: 9443
    ssl_trusted_certificate: /etc/ssl/certs/ca-certificates.crt
    ssl_protocols: TLSv1.2 TLSv1.3
  proxy_cache:
    cache_ttl: 10s
    zones:
    - disk_path: /tmp/disk_cache_one
      cache_levels: '1:2'
      name: disk_cache_one
      memory_size: 50m
      disk_size: 1G
    - memory_size: 50m
      name: memory_cache
  enable_resolv_search_opt: true
  enable_dev_mode: false
  enable_admin: true
stream_plugins:
- ip-restriction
- limit-conn
- mqtt-proxy
- syslog
- traffic-split
etcd:
  prefix: /apisix
  host:
  - http://127.0.0.1:2379
  tls:
    verify: true
  watch_timeout: 50
  startup_retry: 2
  timeout: 30
plugin_attr:
  inspect:
    hooks_file: /usr/local/apisix/plugin_inspect_hooks.lua
    delay: 3
  dubbo-proxy:
    upstream_multiplex_count: 32
  zipkin:
    set_ngx_var: false
  opentelemetry:
    resource:
      service.name: APISIX
    collector:
      request_timeout: 3
      address: 127.0.0.1:4318
      request_headers:
        Authorization: token
    batch_span_processor:
      drop_on_queue_full: false
      max_queue_size: 1024
      batch_timeout: 2
      inactive_timeout: 1
      max_export_batch_size: 16
    trace_id_source: x-request-id
    set_ngx_var: false
  proxy-mirror:
    timeout:
      read: 60s
      send: 60s
      connect: 60s
  log-rotate:
    timeout: 10000
    max_kept: 168
    interval: 3600
    enable_compression: false
    max_size: -1
  skywalking:
    service_instance_name: APISIX Instance Name
    report_interval: 3
    endpoint_addr: http://127.0.0.1:12800
    service_name: APISIX
  prometheus:
    export_uri: /apisix/prometheus/metrics
    metric_prefix: apisix_
    enable_export_server: true
    export_addr:
      port: 9091
      ip: 127.0.0.1
    refresh_interval: 15
  server-info:
    report_ttl: 60
graphql:
  max_size: 1048576
...
